### PR TITLE
src: patch https in Node 8.9 and 9.0

### LINKED ISSUE #589: https.request doesn't work in Node 8.9+
Context: https://github.com/nodejs/node/pull/16395

### PR DESCRIPTION
**Pull request by kjin**
Fixes #589 

Loading either `http` or `https` will cause both to be patched for tracing. This is in line with behavior in <8.9, as `https.request` used to depend on `http.request`.

The only new user-facing change is in the addition of the `https` config field: disabling causes the specific behavior of not patching `https` only if it's loaded before `http` in user-space code. It's a niche use-case so I think this is justifiable, but please let me know your thoughts.

By nature of our loader system this is uncharted territory, so feel free to give suggestions if you think there's a better approach.

### CODE REVIEW

File: config.ts [hunk 1]
```diff
@@ -164,6 +164,7 @@ export const defaultConfig = {
     'grpc': path.join(__dirname, 'src/plugins/plugin-grpc.js'),
     'hapi': path.join(__dirname, 'src/plugins/plugin-hapi.js'),
     'http': path.join(__dirname, 'src/plugins/plugin-http.js'),
+    'https': path.join(__dirname, 'src/plugins/plugin-https.js'),
```
Comment (ofrobots) [inline config.ts]: If I require `https`, that will recursively require `http` hitting the existing plugin. Would that not work?

Comment (kjin) [reply config.ts]: That won't be the case -- the order of events happens like this:

1. call `require('https')`
1. load plugin for `https`
1. load `https`
    1. call `require('http')`
    1. load plugin for `http`
    1. load `http`
    1. patch `http` (and `https`)
1. patch `https` (no op)

We can't patch `https` in (3iv) because it's already been loaded.

So what I'm proposing here is for (3i) thru (3iv) to be moved under (2) rather than (3).

**Comment by kjin** [comment]
AppVeyor CI: https://ci.appveyor.com/project/matthewloring/cloud-trace-nodejs/build/1.0.1848

**Comment by kjin** [comment]
@ofrobots @GoogleCloudPlatform/node-team PTAL when AppVeyor CI is green.

File: src/plugins/plugin-https.ts [hunk 2]
```diff
@@ -0,0 +1,25 @@
...
+
+'use strict';
+
+// Force load http to patch https with the http plugin.
+// https depends on http anyway, so this shouldn't cause an unnecessary load.
+require('http');
+
+module.exports = [];
+
+export default {};
```
Comment (ofrobots) [inline src/plugins/plugin-https.ts]: default exports are not permitted (gts should catch this)

File: src/plugins/plugin-https.ts [hunk 3]
```diff
@@ -0,0 +1,25 @@
...
+ * limitations under the License.
+ */
+
+'use strict';
+
+// Force load http to patch https with the http plugin.
+// https depends on http anyway, so this shouldn't cause an unnecessary load.
+require('http');
+
+module.exports = [];
```
Comment (ofrobots) [inline src/plugins/plugin-https.ts]: It doesn't make sense to use both CJS style exports and ES6 exports in the same file. Which one takes precedence?

File: src/plugins/plugin-http.ts [hunk 4]
```diff
@@ -44,118 +44,139 @@ function extractUrl(options) {
...
-  shimmer.unwrap(http, 'request');
-  if (semver.satisfies(process.version, '>=8.0.0')) {
-    shimmer.unwrap(http, 'get');
-  }
+function isTraceAgentRequest (options, api) {
+  return options && options.headers &&
+    !!options.headers[api.constants.TRACE_AGENT_REQUEST_HEADER];
+}
+
+function makeRequestTrace(request, api) {
```
Comment (ofrobots) [inline src/plugins/plugin-http.ts]: This code reorganization makes it harder to review. Is anything changed in this file?

Comment (kjin) [reply src/plugins/plugin-http.ts]: `makeRequestTrace` and `isTraceAgentRequest` are unchanged except they now each take in an `api` object. They were taken out of `patchHttp` so they can be shared with `patchHttps`.

File: src/plugins/plugin-https.ts (hunk 3 above)
Comment (kjin) [reply src/plugins/plugin-https.ts]: Changing this to `export = []`.

File: src/plugins/plugin-https.ts (hunk 2 above)
Comment (kjin) [reply src/plugins/plugin-https.ts]: Plugins aren't covered by gts -- as they have not been modified (save for the default export to mark the file as a module rather than a script).

That being said, since this is a new file, I can include this file in the list of files to check with gts.

File: src/plugins/plugin-http.ts [hunk 5]
```diff
@@ -44,118 +44,139 @@ function extractUrl(options) {
...
-      options.headers = options.headers || {};
-
-      var uri = extractUrl(options);
-      var requestLifecycleSpan =
-          api.createChildSpan({name: getSpanName(options)});
-      if (!requestLifecycleSpan) {
-        return request.apply(this, arguments);
-      }
+function patchHttps(https, api) {
+  console.log('patch https');
```
Comment (ofrobots) [inline src/plugins/plugin-http.ts]: remove this

File: src/plugins/plugin-http.ts [hunk 6]
```diff
@@ -44,118 +44,139 @@ function extractUrl(options) {
...
+  shimmer.wrap(https, 'request', function requestWrap(request) {
+    return makeRequestTrace(request, api);
+  });
+  shimmer.wrap(https, 'get', function requestWrap(get) {
```
Comment (ofrobots) [inline src/plugins/plugin-http.ts]: `https.get` didn't exist before 8.0.0 as well right? I think this code assumes that you will never reach here because of the semver range in `module.exports` array. It would better to have the logic similar (potentially shared) between http and https rather than having two slightly different copies.

File: src/plugins/plugin-http.ts (hunk 5 above)
Comment (kjin) [reply src/plugins/plugin-http.ts]: 😨

File: src/plugins/plugin-http.ts (hunk 6 above)
Comment (kjin) [reply src/plugins/plugin-http.ts]: I believe whether external/internal `request` is used for `get` is inconsistent between `http` and `https` across different versions of Node. AFAIK:

* `https.get` calls `https.request` for `<8.9.0` and (`>=8.9.1 && <9.0.0`)
* `http.get` calls `http.request` for `<8.0.0`

I think it's more readable to have slightly more duplicated code than have one patch and unpatch function and add an additional parameter that specifies the version range in which `get` must be separately patched/unpatched.
