### PR TITLE
Remove trace span functions from stack traces

### LINKED ISSUE #229: Remove trace agent specific frames from reported stack traces
Right now the top ~4 frames are span logic. We should eliminate these.

### PR DESCRIPTION
**Pull request by matthewloring**
Fixes #229

### CODE REVIEW

**Comment by matthewloring** [comment]
@ofrobots PTAL.

File: lib/hooks/userspace/hook-express.js [hunk 1]
```diff
@@ -83,7 +83,7 @@ function startRootSpanForRequest(req, traceHeader) {
   // we use the path part of the url as the span name and add the full
   // url as a label
   var rootContext = agent.createRootSpanData(req.originalUrl, traceId,
-    parentSpanId);
+    parentSpanId, 3); // Skip 3 frames
```
Comment (ofrobots) [inline lib/hooks/userspace/hook-express.js]: This mechanism will be brittle when we change something in how `createRootSpanData`. `createRootSpanData` should have an idea how how many frames it should skip regardless, and it could accept an argument that is the number of frames to skip *in addition* so that the caller of `createRootSpanData` can skip additional frames.

It would be good to reduce the unnecessary tight coupling here.

Comment (matthewloring) [inline lib/hooks/userspace/hook-express.js]: As discussed in person, this philosophy is applied inside the trace agent but doesn't work here in the hooks.

File: lib/span-data.js [hunk 2]
```diff
@@ -28,10 +28,11 @@ var uid = 1;
  * @param {string} name The name of the span.
  * @param {number} parentSpanId The id of the parent span, 0 for root spans.
  * @param {boolean} isRoot Whether this is a root span.
+ * @param {number} skipFrames the number of frames to remove from the top of the stack.
  * @param {number=} time The time when the associated TraceSpan begins.
```
Comment (ofrobots) [inline lib/span-data.js]: Aside: do we ever call this constructor with the `time` argument in the codebase? Perhaps it should be dropped (in a follow-on)

File: test/hooks/test-trace-restify.js [hunk 3]
```diff
@@ -26,7 +26,7 @@ var versions = {
 
 var server;
 
-Object.keys(versions).forEach(function(version) {
+Object.keys(versions).forEach(function(version, i) {
```
Comment (ofrobots) [inline test/hooks/test-trace-restify.js]: Do you use the index anywhere? It is hard to search for `i` – I can't find it by eyeballing the code.

**Comment by ofrobots** [comment]
lgtm w/ nits.

File: lib/span-data.js (hunk 2 above)
Comment (matthewloring) [inline lib/span-data.js]: Good catch. Wiping it out here since it is never used.

File: test/hooks/test-trace-restify.js (hunk 3 above)
Comment (matthewloring) [inline test/hooks/test-trace-restify.js]: Nope, was used for testing but not needed anymore.
