### PR TITLE
Some cleanups, and fix for span warnings on own requests

### LINKED ISSUE #4: Remove warnings for own context-less outgoing http requests

### PR DESCRIPTION
**Pull request by ofrobots**
Fixes #4.

### CODE REVIEW

File: lib/utils.js [hunk 1]
```diff
@@ -123,23 +123,27 @@ function authorizedRequestFactory(scopes) {
...
+    headers = {};
   }
 
+  headers['Metadata-Flavor'] = 'Google';
+
   var request = require('request');
   requestWithRetry(request, {
-    url: 'http://metadata/computeMetadata/v1/project/numeric-project-id',
-    headers: { 'Metadata-Flavor': 'Google'},
+    url: 'http://metadata.google.internal/computeMetadata/v1/project/' +
```
Comment (matthewloring) [inline lib/utils.js]: Do we want to move URLs into constants as well?

Comment (ofrobots) [inline lib/utils.js]: Good idea in general, but this one I am hesitant to move because I want to extract utils into a separate module.

File: lib/trace-writer.js [hunk 2]
```diff
@@ -17,10 +17,15 @@
 'use strict';
 
 var utils = require('./utils.js');
+var constants = require('./constants.js');
+var pjson = require('../package.json');
 
 /* @const {Array<string>} list of scopes needed to operate with the trace API */
 var SCOPES = ['https://www.googleapis.com/auth/trace.append'];
```
Comment (matthewloring) [inline lib/trace-writer.js]: Another contender for constants?

File: index.js [hunk 3]
```diff
@@ -67,7 +72,7 @@ var publicAgent = {
     var logger = new Logger(config.logLevel, '@google/cloud-trace');
```
Comment (matthewloring) [inline index.js]: Maybe a constant?

**Comment by matthewloring** [comment]
LGTM. I pointed out a few other potential constants but they don't need to go in right now.

File: index.js (hunk 3 above)
Comment (ofrobots) [inline index.js]: It is not used anywhere else, and is a very descriptive value. It is better left inline here.

File: lib/trace-writer.js (hunk 2 above)
Comment (ofrobots) [inline lib/trace-writer.js]: It is not exported or used in any other file, so there is no benefit from moving it to constants.
