### PR TITLE
Attempt to publish traces on unhandled exception

### LINKED ISSUE #232: Agent should attempt to publish traces on unhandled exception

### PR DESCRIPTION
**Pull request by matthewloring**
Fixes #232

### CODE REVIEW

**Comment by matthewloring** [comment]
@ofrobots PTAL.

File: test/standalone/test-trace-uncaught-exception.js [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+var cls = require('../../lib/cls.js');
+var agent = require('../..');
+var request = require('request');
+
+nock.disableNetConnect();
+
+var uri = 'https://cloudtrace.googleapis.com';
+var path = '/v1/projects/0/traces';
+
+process.env.GCLOUD_PROJECT_NUM = 0;
```
Comment (ofrobots) [inline test/standalone/test-trace-uncaught-exception.js]: Probably need to update this.

Comment (matthewloring) [inline test/standalone/test-trace-uncaught-exception.js]: Done.

File: config.js [hunk 2]
```diff
@@ -60,6 +60,18 @@ module.exports = {
...
     // The number of transactions we buffer before we publish to the Cloud Trace
     // API, unless we hit `flushDelaySeconds` first.
-    bufferSize: 1000
+    bufferSize: 1000,
+
+    // If true, the trace agent will attempt to publish any buffered traces if an
+    // uncaught exception occurs. This will result in the error being silenced. If
+    // you want your application to exit on uncaught exception you will have to
+    // add your own listener to the 'uncaughtException' event on the process.
+    publishOnUncaught: false,
```
Comment (ofrobots) [inline config.js]: Another idea would be to expose a single option `onUncaughtExcpetion` that has the following behaviours:
* falsy: we don't deal with uncaught exceptions
* 'flush': flush the buffer, and silence the error
* 'flushAndExit': flushes then exits.

WDYT?

Comment (matthewloring) [inline config.js]: I am not personally a fan of using strings as enums in configuration. If we want to reduce the configuration surface area, I would prefer offering a single `flushAndExit` boolean. If people are going to be recovering and silencing the errors then they would likely not care that we don't flush when the process would otherwise have gone down. Would this be acceptable?

Comment (matthewloring) [inline config.js]: Going with ternary enum approach.

File: index.js [hunk 3]
```diff
@@ -133,6 +135,12 @@ var publicAgent = {
       logger.info('Locally provided ProjectId: ' + config.projectId);
     }
 
+    if (onUncaughtExceptionValues.indexOf(config.onUncaughtException) === -1) {
+      logger.error('The value of onUncaughtException should be one of ',
+        onUncaughtExceptionValues);
+      process.exit(1);
```
Comment (ofrobots) [inline index.js]: nit: throw instead of exiting.

File: config.js [hunk 4]
```diff
@@ -60,6 +60,13 @@ module.exports = {
 
     // The number of transactions we buffer before we publish to the trace
     // API, unless we hit `flushDelaySeconds` first.
-    bufferSize: 1000
+    bufferSize: 1000,
+
+    // Specifies the behavior of the trace agent in the case of an uncaught exception.
+    // Possible values are:
+    //   `disregard`: Take no action.
```
Comment (ofrobots) [inline config.js]: 🚲🏡  time!

Can we use `'ignore'` instead of `'disregard'`?

**Comment by ofrobots** [comment]
LGTM w/ nits.

File: config.js (hunk 4 above)
Comment (matthewloring) [inline config.js]: Done.

File: index.js (hunk 3 above)
Comment (matthewloring) [inline index.js]: Done.
