### PR TITLE
fix: allow non-objects for plugins to disable automatic tracing

### LINKED ISSUE #719: Option to disable automatic tracing
Hello,

Is there any way to disable automatic tracing altogether? It would be nice if this module exposed a simple span tracing API. 

Thanks

### PR DESCRIPTION
**Pull request by kjin**
Fixes #719 

This change allows users to disable automatic tracing by passing a non-object value (such as `false`) for the value of `config.plugins`. It takes advantage of `extend`'s behavior of allowing non-object values to override object values, and vice versa.

Since we do not recommend disabling plugins I have not documented this feature.

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -89,7 +89,9 @@ function initConfig(projectConfig: Forceable<Config>):
   // 4. Default Config (as specified in './config')
   const config = extend(
       true, {[FORCE_NEW]: projectConfig[FORCE_NEW]}, defaultConfig,
-      envSetConfig, projectConfig, envConfig);
+      envSetConfig, projectConfig, envConfig, {plugins: {/**/}});
```
Comment (ofrobots) [inline src/index.ts]: Remove the comment from the object?
